# Generated by Django 4.0.4 on 2022-04-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='default_cat.png', upload_to='cats_images', verbose_name='Image')),
                ('breed', models.CharField(max_length=150, verbose_name='Breed')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Price in $')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
    ]
